runtime: nodejs14
env_variables:
  SQL_HOST: 34.145.184.24
  SQL_USER: app_access
  SQL_PASSWORD: wonton_soup
  SQL_DATABASE: mturk_sg
  INSTANCE_CONNECTION_NAME: wilder-breakthroughs:us-east4:sequence-labeler
  SQ_SQL_USER: app_access
  SQ_SQL_PASSWORD: wonton_soup
  SQ_SQL_DATABASE: sequence_labeler
beta_settings:
  cloud_sql_settings: wilder-breakthroughs:us-east4:sequence-labeler 